### ISSUE TITLE
Replace repository

### ISSUE THREAD

**Issue by pincher2012** [jamesrwhite/sphinx-alpine-docker#1]
Sphinx in community folder now. Replace `http://dl-5.alpinelinux.org/alpine/edge/testing` to `http://dl-5.alpinelinux.org/alpine/edge/community`. https://pkgs.alpinelinux.org/package/edge/community/x86/sphinx

**Comment by jamesrwhite** [comment]
This was fixed in https://github.com/jamesrwhite/sphinx-alpine-docker/commit/19b4578b4b303b8da778d273b1ebc506a3d98028
